Resources:
    GamesTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ${self:custom.tableName}
            AttributeDefinitions:
                - AttributeName: userId
                  AttributeType: S
                - AttributeName: date_machine
                  AttributeType: S
            KeySchema:
                - AttributeName: userId
                  KeyType: HASH
                - AttributeName: date_machine
                  KeyType: RANGE
            # Set the capacity to auto-scale
            BillingMode: PAY_PER_REQUEST
